import type { AppData } from "./type";

export const MOCK_DATA: AppData = {
  user: {
    name: "Mona",
  },
  todaySchedule: [
    {
      id: 1,
      title: "Prepare project proposal",
      status: "pending",
      priority: "high",
      duration: "2h",
      description: "Draft the initial project proposal for client review.",
      assignedPeriod: {
        start: new Date("2025-09-30T09:00:00"),
        end: new Date("2025-09-30T11:00:00"),
      },
      deadline: "2025-10-01",
      completed: false,
    },
    {
      id: 2,
      title: "Team daily standup",
      status: "done",
      priority: "medium",
      duration: "30m",
      assignedPeriod: {
        start: new Date("2025-09-29T10:00:00"),
        end: new Date("2025-09-29T10:30:00"),
      },
      completed: true,
    },
    {
      id: 3,
      title: "Update Jira tickets",
      status: "missed",
      priority: "low",
      duration: "1h",
      description: "Go through open tickets and update statuses.",
      deadline: "2025-09-28",
      completed: false,
    },
    {
      id: 4,
      title: "1:1 with Alex",
      status: "pending",
      priority: "medium",
      duration: "45m",
      assignedPeriod: {
        start: new Date("2025-09-30T14:00:00"),
        end: new Date("2025-09-30T14:45:00"),
      },
      completed: false,
    },
    {
      id: 5,
      title: "Client feedback session",
      status: "canceled",
      priority: "high",
      duration: "1h",
      description: "Meeting canceled by client.",
      completed: false,
    },
    {
      id: 6,
      title: "Design review",
      status: "done",
      priority: "high",
      duration: "1.5h",
      assignedPeriod: {
        start: new Date("2025-09-27T13:00:00"),
        end: new Date("2025-09-27T14:30:00"),
      },
      completed: true,
    },
    {
      id: 7,
      title: "Prepare slides for presentation",
      status: "pending",
      priority: "high",
      duration: "3h",
      deadline: "2025-10-02",
      completed: false,
    },
    {
      id: 8,
      title: "Database backup",
      status: "done",
      priority: "low",
      duration: "2h",
      description: "Automated backup completed successfully.",
      completed: true,
    },
    {
      id: 9,
      title: "Write unit tests",
      status: "pending",
      priority: "medium",
      duration: "4h",
      assignedPeriod: {
        start: new Date("2025-09-30T15:00:00"),
        end: new Date("2025-09-30T19:00:00"),
      },
      completed: false,
    },
    {
      id: 10,
      title: "Fix bug in login flow",
      status: "missed",
      priority: "high",
      duration: "2h",
      deadline: "2025-09-29",
      completed: false,
    },
    {
      id: 11,
      title: "Marketing strategy call",
      status: "pending",
      priority: "medium",
      duration: "1h",
      assignedPeriod: {
        start: new Date("2025-10-01T11:00:00"),
        end: new Date("2025-10-01T12:00:00"),
      },
      completed: false,
    },
    {
      id: 12,
      title: "Review code PR #342",
      status: "done",
      priority: "medium",
      duration: "45m",
      completed: true,
    },
    {
      id: 13,
      title: "Sprint retrospective",
      status: "pending",
      priority: "high",
      duration: "1h",
      assignedPeriod: {
        start: new Date("2025-10-02T16:00:00"),
        end: new Date("2025-10-02T17:00:00"),
      },
      completed: false,
    },
    {
      id: 14,
      title: "Server maintenance",
      status: "canceled",
      priority: "low",
      duration: "3h",
      description: "Canceled due to infra upgrade.",
      completed: false,
    },
    {
      id: 15,
      title: "Draft blog post",
      status: "pending",
      priority: "medium",
      duration: "2h",
      deadline: "2025-10-03",
      completed: false,
    },
    {
      id: 16,
      title: "QA testing round",
      status: "done",
      priority: "high",
      duration: "5h",
      completed: true,
    },
    {
      id: 17,
      title: "Organize files",
      status: "pending",
      priority: "low",
      duration: "1h",
      completed: false,
    },
    {
      id: 18,
      title: "Demo with stakeholders",
      status: "pending",
      priority: "high",
      duration: "1h",
      assignedPeriod: {
        start: new Date("2025-10-04T09:30:00"),
        end: new Date("2025-10-04T10:30:00"),
      },
      completed: false,
    },
    {
      id: 19,
      title: "Security patch update",
      status: "done",
      priority: "medium",
      duration: "2h",
      completed: true,
    },
    {
      id: 20,
      title: "Plan Q4 roadmap",
      status: "pending",
      priority: "high",
      duration: "3h",
      assignedPeriod: {
        start: new Date("2025-10-05T14:00:00"),
        end: new Date("2025-10-05T17:00:00"),
      },
      deadline: "2025-10-06",
      completed: false,
    },
  ],
  goals: [
    {
      id: 1,
      title: "Launch New Feature",
      progress: 75,
      description: "Finalizing UI components and integrating API endpoints.",
    },
    { id: 2, title: "Complete Q3 OKRs", progress: 40 },
    { id: 3, title: "Onboard new hire", progress: 90 },
  ],
  chatHistory: [
    {
      from: "user",
      text: "Hey, can you help me organize my tasks for tomorrow?",
    },
    {
      from: "ai",
      text: "Of course, Mona! Just list them out and I'll create a prioritized schedule for you.",
    },
    {
      from: "user",
      text: "Okay: finish report, call mom, gym, buy groceries, team sync",
    },
    { from: "ai", type: "typing" },
  ],
  progress: {
    summary: { completed: 80, mostProductive: "10am", missed: 2 },
    heatmap: [
      { date: "2025-09-01", count: 2 },
      { date: "2025-09-02", count: 4 },
      { date: "2025-09-03", count: 1 },
      { date: "2025-09-04", count: 5 },
      { date: "2025-09-05", count: 0 },
      { date: "2025-09-06", count: 3 },
      { date: "2025-09-07", count: 5 },
      { date: "2025-09-08", count: 4 },
      { date: "2025-09-09", count: 1 },
      { date: "2025-09-10", count: 2 },
      { date: "2025-09-11", count: 5 },
      { date: "2025-09-12", count: 4 },
      { date: "2025-09-13", count: 3 },
      { date: "2025-09-14", count: 0 },
      { date: "2025-09-15", count: 5 },
    ],
  },
};
